# Generated by Django 3.1.6 on 2021-03-31 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_two_factor_face_auth.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_two_factor_face_auth', '0005_auto_20210214_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufile', models.FileField(upload_to=django_two_factor_face_auth.models.content_ufile_name)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
