# Generated by Django 3.1.6 on 2021-03-31 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_two_factor_face_auth', '0006_userfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFiles',
            new_name='UserFile',
        ),
    ]
